<?php

declare(strict_types=1);

namespace Gisl\Sdk\FileFirst;

use Gisl\Sdk\Ergonomic\OperationBuilder;
use Gisl\Sdk\Errors\GislConfigError;

/**
 * The primary file a {@see Recipe} operates on — the "subject" of the
 * file-first surface. A discriminated value over the three ways a caller
 * can name an input:
 *
 *  - `path`      — a local filesystem path (the common case, examples 01/02).
 *  - `resource`  — an open PHP stream/resource handle.
 *  - `uploadId`  — a previously-uploaded `file_id` (reuse across recipes).
 *
 * FF2a does NO upload, so only the `path` + `uploadId` arms are exercised
 * end-to-end here; the `resource` arm is DEFINED and type-checked but its
 * upload is wired by FF2b (`run()`). Mirrors the TS `FileInput` union in
 * `packages/typescript/src/file-first.ts`.
 *
 * Immutable: all properties are readonly and the only constructor is private,
 * reached through the three named factories.
 */
final class FileInput
{
    public const KIND_PATH = 'path';
    public const KIND_RESOURCE = 'resource';
    public const KIND_UPLOAD_ID = 'upload_id';

    /**
     * @param self::KIND_*  $kind        Which arm of the union is populated.
     * @param string|null   $path        Filesystem path when `$kind === KIND_PATH`.
     * @param resource|null $resource    Open stream when `$kind === KIND_RESOURCE`.
     * @param string|null   $fileId      Pre-uploaded id when `$kind === KIND_UPLOAD_ID`.
     * @param string|null   $filename    Optional name hint for a resource input
     *        (extension drives local media inference + the upload's multipart filename).
     * @param string|null   $contentType Optional MIME hint for a resource input
     *        (canonical media signal, mirrors a browser `Blob.type`).
     */
    private function __construct(
        public readonly string $kind,
        public readonly ?string $path = null,
        public readonly mixed $resource = null,
        public readonly ?string $fileId = null,
        public readonly ?string $filename = null,
        public readonly ?string $contentType = null,
    ) {
    }

    public static function path(string $path): self
    {
        return new self(self::KIND_PATH, path: $path);
    }

    /**
     * Reference an open, **seekable** stream resource as an input (the
     * in-memory / Blob analogue, VOxtu0RZ-B4) — e.g. a `php://temp` handle
     * holding generated bytes. A non-seekable stream (`php://stdin`, a pipe)
     * is rejected at upload time with an actionable error; buffer it to a temp
     * path first. The caller owns the stream's lifecycle (the SDK never closes
     * it).
     *
     * A stream carries no filename/MIME of its own, so a media-dependent op
     * (`compress(optimize: ...)`) cannot infer a preset and would fail before
     * upload. Pass `$filename` and/or `$contentType` (fFwaKsN5) so in-memory
     * media works through the ergonomic file-first path without dropping to
     * the low-level `uploadFile()` + `FileInput::uploadId()` plumbing — the PHP
     * analogue of a browser `Blob`/`File` carrying `.name`/`.type`.
     *
     * @param resource    $resource
     * @param string|null $filename    Name hint — its extension drives media inference
     *        and becomes the upload's multipart filename (e.g. `'photo.jpg'`).
     * @param string|null $contentType MIME hint — the canonical media signal,
     *        preferred over the filename extension (e.g. `'image/jpeg'`).
     */
    public static function resource(mixed $resource, ?string $filename = null, ?string $contentType = null): self
    {
        if (!\is_resource($resource)) {
            throw new GislConfigError(
                'FileInput::resource() expected an open stream resource; got ' . \get_debug_type($resource) . '.',
            );
        }
        return new self(self::KIND_RESOURCE, resource: $resource, filename: $filename, contentType: $contentType);
    }

    /**
     * Reference an already-uploaded file by its upload id, instead of
     * re-uploading bytes.
     *
     * Auth-ownership: an upload created by an *authenticated* caller is owned
     * by that caller. If you reuse the id from a client configured with a
     * DIFFERENT auth context (a different api key / session), workflow-create
     * returns `404 upload_not_found` — the server enforces ownership (api
     * PqpD9ySv). Reference an upload id only under the SAME auth that created
     * it. The normal upload-then-create-in-one-client flow is consistent by
     * construction (the same Authorization rides every request). Ownerless
     * (anonymous-intake) uploads are unaffected.
     */
    public static function uploadId(string $fileId): self
    {
        return new self(self::KIND_UPLOAD_ID, fileId: $fileId);
    }

    /**
     * The compress media class for preset resolution, derived from the input's
     * filename extension (path inputs) or the `contentType`/`filename` hints
     * (resource inputs, fFwaKsN5) — or null when the media cannot be inferred
     * locally (a hint-less resource or a bare upload id). Reuses the same
     * classifiers the operation-first builder uses so a file-first `compress()`
     * lowers to the identical wire options as `client->compress()`.
     *
     * For a resource the MIME hint is canonical (preferred), then the filename
     * extension — mirroring the TS `_detectCompressMedia` Blob branch (MIME-first).
     *
     * @return 'image'|'audio'|'video'|'document_office'|'document_odf'|'document_epub'|'document_pdf'|null
     */
    public function compressMediaHint(): ?string
    {
        if ($this->kind === self::KIND_PATH && $this->path !== null) {
            return OperationBuilder::detectCompressMedia($this->path);
        }
        if ($this->kind === self::KIND_RESOURCE) {
            if ($this->contentType !== null) {
                $fromMime = OperationBuilder::detectCompressMediaFromMime($this->contentType);
                if ($fromMime !== null) {
                    return $fromMime;
                }
            }
            if ($this->filename !== null) {
                return OperationBuilder::detectCompressMedia($this->filename);
            }
        }
        return null;
    }

    /**
     * Best-effort LOSSLESS-audio classification (flac/wav) for the preset
     * resolver, derived from the same hints as {@see compressMediaHint()}: the
     * filename extension (path inputs) or the `contentType`/`filename` hints
     * (resource inputs). MIME-first for resources, mirroring the TS
     * `_detectAudioLossless` Blob branch. Returns false when the input carries
     * no inferable signal — the worker stays authoritative on the bitrate.
     */
    public function compressAudioLosslessHint(): bool
    {
        if ($this->kind === self::KIND_PATH && $this->path !== null) {
            return OperationBuilder::detectAudioLossless($this->path);
        }
        if ($this->kind === self::KIND_RESOURCE) {
            if ($this->contentType !== null && \str_starts_with($this->contentType, 'audio/')) {
                return OperationBuilder::detectAudioLosslessFromMime($this->contentType);
            }
            if ($this->filename !== null) {
                return OperationBuilder::detectAudioLossless($this->filename);
            }
        }
        return false;
    }
}
